<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>


<div id="container" style="height: 400px;"></div>
 

		
		

<script>

var chart;
$(document).ready(function() {
	chart = new Highcharts.Chart({
		chart: {
			renderTo: 'container',
			backgroundColor: '#cccccc',
			plotBorderWidth: null,
			plotShadow: false
			
		},
		title: {
			text: 'gastos'
		},
		
		tooltip: {
			formatter: function() {
				var y = this.y;
				var p = Math.round(this.percentage*100)/100;
				return '<b>'+ this.point.name +'</b>: ' + y + ' euros (' + p + '%)';
			}
		},
		plotOptions: {
			pie: {
				allowPointSelect: true,
				
				cursor: 'pointer',
				dataLabels: {
					enabled: false
				},
				showInLegend: true
			}
		},
		series: [{
			type: 'pie',
			name: 'overall',
			backgroundColor: '#cccccc',
			point: {
				events: {
					click: function(e) {
						//this.slice();
						//console.log(e);
						location.href = e.point.url;
						e.preventDefault();
					}
				}
			},
			data: [
				<?php echo $this->absGasto(); ?>
				
					
				
			]
		}]
	});
});
</script>