<?php
// module/Camara/view/camara/camara/index.phtml
$title = 'Selecionar distrito';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<tr>
    <th>Distrito</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($distrito as $cam) : ?>
<tr>
    <td><?php echo $this->escapeHtml($cam->distrito);?></td>
    
    <td>
        <a href="<?php echo $this->url('candidatura',
            array('action'=>'distrito', 'id' => $cam->id));?>">Ver listas inscritas neste distrito</a>
    </td>
    <td>
        <a href="<?php echo $this->url('postcartaz',
            array('action'=>'distrito', 'id' => $cam->id));?>">Ver cartazes deste distrito</a>
    </td>
    <td>
        <a href="<?php echo $this->url('camara',
            array('action'=>'index', 'id' => $cam->id));?>">Addicionar cartaz neste distrito</a>
    </td>
    <td>
        <a href="<?php echo $this->url('camara',
            array('action'=>'index', 'id' => $cam->id));?>">Addicionar lista neste distrito</a>
    </td>
</tr>

<?php endforeach; ?>
</table>

