<div class="container">
	<div class="blog_container">
			<div class="row-full clearfix">
				<div class="spanx">
					<img width="940" alt="" src="/assets/cartaz/<?php echo $cartaz->getImage();?>">
				</div>
			</div>
			<div class="row-full clearfix">
				<ul class="thumbnails" >
					<li class="span5" style="margin-top:50px;">
						<div><?php echo $this->map_html;?></div>
							
					
					<li class="span4" style="margin-top:50px;">
						<div>
							<ul>
	              				<li>Distrito : <?php echo $cartaz->getIdLista()->getIdCamara()->getIdDistrito()->getNome();?></li>
	              				<li>Concelho : <?php echo $cartaz->getIdLista()->getIdCamara()->getNome();?></li>
	              				<li>Nome do partido : <?php echo $cartaz->getIdLista()->getNome();?></li>
	              				<li>Morada : <?php echo $cartaz->getMorada();?></li>
	              			</ul>
	              		</div>
					</div>
				</ul>
			</div>
	</div>
			
