<?php // module/PostCartaz/view/post-cartaz/post-cartaz/distrito.phtml:?>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<h1><?php echo $this->escapeHtml('Cartazes do distrito '.$distrito->getNome()); ?></h1>
</br>
</br>

<div id="highroller"></div>
<?php
    $this->highroller->chart->renderTo = "highroller";
    echo $this->headScript()->appendScript($this->highroller->renderChart());
?>



<select onchange="javascript:location.href='/post-cartaz/camara/'+this.options
    [this.selectedIndex].value;">
        <option selected="selected">Concelhos</option>
	<?php foreach ($camaras as $cam) : ?>
	<option VALUE="<?php echo $cam->id;?>">
	<?php echo $cam->nome;?></option>

<?php endforeach; ?>

</select>

</br>
</br>

<p>
<a class="btn btn-custom" href="<?php echo $this->url('postcartaz', array('action'=>'global'));?>">Voltar a pagina anterior</a>
</p>