<?php // module/PostCartaz/view/post-cartaz/post-cartaz/global.phtml:?>
<?php


  if(count($flashSucess)) : ?>
	<div class="alert alert-success fade in">
    	<button type="button" class="close" data-dismiss="alert">x</button>
    	<?php foreach ($flashSucess as $msg) : ?>
    		<?php echo $msg; ?><br />
    	<?php endforeach; ?>
    	
    </div>
<?php endif; ?>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<div id="highroller"></div>
<?php
    $this->highroller->chart->renderTo = "highroller";
    echo $this->headScript()->appendScript($this->highroller->renderChart());
?>


<select onchange="javascript:location.href='/post-cartaz/distrito/'+this.options
    [this.selectedIndex].value;">
        <option selected="selected">Distritos</option>
        <option VALUE="1">A&ccedil;ores</option>
        <option VALUE="2">Aveiro</option>
        <option VALUE="3">Beja</option>
        <option VALUE="4">Braga</option>
        <option VALUE="5">Bragan&ccedil;a</option>
        <option VALUE="6">castelo Branco</option>
        <option VALUE="7">Coimbra</option>
        <option VALUE="8">&Eacute;vora</option>
        <option VALUE="9">Faro</option>
        <option VALUE="10">Guarda</option>
        <option VALUE="11">Leira</option>
        <option VALUE="12">Lisboa</option>
        <option VALUE="13">Madeira</option>
        <option VALUE="14">Portalegre</option>
        <option VALUE="15">Porto</option>
        <option VALUE="16">Santar&eacute;m</option>
        <option VALUE="17">Set&uacute;bal</option>
        <option VALUE="18">Viana do Castelo</option>
        <option VALUE="19">Vila Real</option>
        <option VALUE="20">Viseu</option>
</select>

</br>
</br>

<p>
    <a class="btn btn-custom" href="<?php echo $this->url('backhome', array('action'=>'index',));?>">Voltar a P&aacute;gina Principal</a>
</p>

