<?php // module/PostBrinde/view/post-brinde/post-brinde/index.phtml:?>

<?php if(count($flashMessages)) : ?>
	<div class="alert alert-success fade in">
    	<button type="button" class="close" data-dismiss="alert">x</button>
    	<?php foreach ($flashMessages as $msg) : ?>
    		<?php echo $msg; ?><br />
    	<?php endforeach; ?>
    	
    </div>
<?php endif; ?>

<h1><?php echo $this->escapeHtml('Escolhe um distrito'); ?></h1>
</br>
</br>

<select onchange="javascript:location.href='/post-brinde/distrito/'+this.options
    [this.selectedIndex].value;">
        <option selected="selected">Distritos</option>
        <option VALUE="1">A&ccedil;ores</option>
        <option VALUE="2">Aveiro</option>
        <option VALUE="3">Beja</option>
        <option VALUE="4">Braga</option>
        <option VALUE="5">Bragan&ccedil;a</option>
        <option VALUE="6">castelo Branco</option>
        <option VALUE="7">Coimbra</option>
        <option VALUE="8">&Eacute;vora</option>
        <option VALUE="9">Faro</option>
        <option VALUE="10">Guarda</option>
        <option VALUE="11">Leira</option>
        <option VALUE="12">Lisboa</option>
        <option VALUE="13">Madeira</option>
        <option VALUE="14">Portalegre</option>
        <option VALUE="15">Porto</option>
        <option VALUE="16">Santar&eacute;m</option>
        <option VALUE="17">Set&uacute;bal</option>
        <option VALUE="18">Viana do Castelo</option>
        <option VALUE="19">Vila Real</option>
        <option VALUE="20">Viseu</option>
</select>


<table class="table">
<tr>
<th>Distrito</th>
<th>C&acirc;mara</th>
<th>Partido</th>
<th>Enviado Por</th>
<th></th>
<th>Foto do Brinde</th>
<?php if($identity != null){?>
<th></th>
<?php }?>
<th>Votos</th>
<?php if($identity != null){?>
<th></th>
<th></th>
<?php }?>
</tr>
<?php if(isset($brinde)){?>
<?php foreach ($brinde as $cam) : ?> 
<?php $i=0; 
foreach ($votes as $vote):
if($vote->getIdBrinde()->getIdBrinde() == $cam->getIdBrinde())
{
	if($vote->getRating()==1):
	$i++;
	endif;
}
	
endforeach;


?>

<tr>
	<td><?php echo $cam->getIdLista()->getIdcamara()->getIdDistrito()->getNome()?></td>
	<td><?php echo $cam->getIdLista()->getIdcamara()->getNome()?></td>
	<td><?php echo $cam->getIdLista()->getNome();?></td>
	<td><?php echo $cam->getIdUser()->getUsername();?></td>
	<td><?php echo $cam->getNome();?></td>
    <td><img width="256" alt="" src="/assets/brinde/thumbs/<?php echo $cam->getImage();?>">
    <?php if($identity === null):?>
    <p>Para votar, &eacute; necess&aacute;rio estar logado ou registado. Por favor fa&ccedil;a <a href="<?php echo '/user/login/2';?>">Login</a> ou <a href="<?php echo $this->url('user',
		array('action'=>'registo'));?>">Registe-se</a></p></td>
    <?php else:?>
    </td>
    <td style="padding-top:60px">
    <a class="btn btn-custom" href="post-brinde/upvote/<?php echo $cam->getIdBrinde()?>">+</a>
    <a class="btn btn-custom" href="post-brinde/downvote/<?php echo $cam->getIdBrinde()?>">-</a></td>
    <?php endif; ?>
    
	<?php if($i == 1){ ?>
	<td><?php  echo $i.' ';?> voto</td>
	<?php } else {?>
	<td><?php  echo $i.' ';?> votos</td>
	<?php } ?>

	
	    <?php if($identity != null && $identity->user_group == 1): ?>
    	<td><a class="btn btn-custom" href="/post-brinde/edit/<?php echo $cam->getIdBrinde();?>">Editar</a></td>
    	<td><a class="btn btn-custom" href="/post-brinde/delete/<?php echo $cam->getIdBrinde();?>">Apagar</a></td>
    <?php endif;?>
</tr>
<?php endforeach;} ?>
</table>

<?php 	echo $this->paginationControl($this->brinde,
								  	  'Sliding',
 array('partial/paginator.phtml','post-brinde'),
				  array('route' => 'paginatorbrinde1')); 
?>
<p>
<a class="btn btn-custom" href="<?php echo $this->url('backhome', array('action'=>'index',));?>">Voltar a P&aacute;gina Principal</a>
</p>

