<?php // module/PostBrinde/view/post-brinde/post-brinde/moderate.phtml:?>


<table class="table">
<tr>
<th></th>
<th>Distrito</th>
<th>C&acirc;mara</th>
<th>Partido</th>
<th>Nome</th>
<th>Descri&ccedil;&atilde;o</th>
<th>Enviado Por</th>


</tr>
<?php if(isset($brinde)){?>
<?php foreach ($brinde as $cam) : ?> 

<tr>
	<td><img width="256" alt="" src="/assets/brinde/thumbs/<?php echo $cam->getImage();?>"></td>
	<td><?php echo $cam->getIdLista()->getIdcamara()->getIdDistrito()->getNome()?></td>
	<td><?php echo $cam->getIdLista()->getIdcamara()->getNome()?></td>
	<td><?php echo $cam->getIdLista()->getNome();?></td>
	<td><?php echo $cam->getNome()?></td>
	<td><?php echo $cam->getdescricao();?></td>
	<td><?php echo $cam->getIdUser()->getUsername();?></td>
    
    <td>
    <a class="btn btn-custom " href="/post-brinde/activate/<?php echo $cam->getIdBrinde()?>">Activar</a>
    <a class="btn btn-custom " href="/post-brinde/edit/<?php echo $cam->getIdBrinde()?>">Editar</a>
    <a class="btn btn-custom " href="/post-brinde/delete/<?php echo $cam->getIdBrinde()?> " onclick="return confirm('Tem a certeza ?')">Apagar</a></td>
	

</tr>
<?php endforeach;} ?>
</table>

<?php 	echo $this->paginationControl($this->brinde,
								  	  'Sliding',
 array('partial/paginator.phtml','PostBrinde'),
				  array('route' => 'postbrindemoderate')); 



