<?php
// module/User/view/user/user/login.phtml:

?>
<?php if(count($flashError)) : ?>
	<div class="alert alert-error fade in">
    	<button type="button" class="close" data-dismiss="alert">x</button>
    	<?php foreach ($flashError as $msg) : ?>
    		<?php echo $msg; ?><br />
    	<?php endforeach; ?>
    	
    </div>
<?php endif; ?>
<h1><?php echo $this->escapeHtml('Login'); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'login','id'=>$id,'id2'=>$id2)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</br>
</br>
</br>
</br>
</br>
</br>
<p>
<a class="btn btn-custom " href="<?php echo $this->url('user', array('action'=>'registo'));?>">Regista-se</a>
</p>