<?php // module/Festa/view/festa/festa/camara.phtml:?>



<?php if(count($flashMessages)) : ?>
	<div class="alert alert-success fade in">
    	<button type="button" class="close" data-dismiss="alert">x</button>
    	<?php foreach ($flashMessages as $msg) : ?>
    		<?php echo $msg; ?><br />
    	<?php endforeach; ?>
    	
    </div>
<?php endif; ?>

<h1><?php echo $this->escapeHtml(utf8_encode('Ações de Campanha de '.$camara->getNome())); ?></h1>

</br>
</br>

<select
	onchange="javascript:location.href='/festa/camara/'+this.options
    [this.selectedIndex].value;">
	<option selected="selected">Concelhos</option>
	<?php foreach ($camaras as $cam) : ?>
	<option VALUE="<?php echo $cam->getIdCamara();?>">
	<?php echo $cam->getNome();?></option>

<?php endforeach; ?>

</select>


<?php $k=0; $j=0;
?>
<?php if(isset($festas)){?>
<?php foreach ($festas as $cam) : ?> 

<?php if($cam->getIdLista()->getIdCamara()->getIdCamara()==$id)?>


<?php 
$i=0;
foreach ($votes as $vote):
if($vote->getIdFesta()->getIdFesta() == $cam->getIdFesta())
{
	
	if($vote->getRating()==1):
	$i++;
	endif;
}
	
endforeach;

?>
<table class="table">

	<tr>
		<th>Distrito</th>
		<th>C&acirc;mara</th>
		<th>Com&iacute;cio / Espet&aacute;culo</th>
		<th>Partido</th>
		<th>Morada Inserida</th>
		<th></th>
		<th>votos</th>
		<th></th>
		
	</tr>
	<tr>
		<td><?php echo $cam->getIdLista()->getIdcamara()->getIdDistrito()->getNome()?></td>
		<td><?php echo $cam->getIdLista()->getIdcamara()->getNome()?></td>
		<td><?php echo $cam->getNome();?></td>
		<td><?php echo $cam->getIdLista()->getNome();?></td>
		<td><?php echo $cam->getMorada();?></td>
		<?php if($identity === null):?>
    <p>Para votar, &eacute; necess&aacute;rio estar logado ou registado. Por favor fa&ccedil;a <a href="<?php echo '/user/login/5/'.$idDistrito;?>">Login</a> ou <a href="<?php echo $this->url('user',
		array('action'=>'registo'));?>">Registe-se</a></p>
    <?php else:?>
    <td><a class="btn btn-custom" href="/festa/upvote/<?php echo $cam->getIdFesta()?>/<?php echo $cam->getIdLista()->getIdCamara()->getIdDistrito()->getIdDistrito()?>">+</a>
    	   <a class="btn btn-custom" href="/festa/downvote/<?php echo $cam->getIdFesta()?>/<?php echo $cam->getIdLista()->getIdCamara()->getIdDistrito()->getIdDistrito()?>">-</a></td>
    <?php endif; ?>
		
    	<td><?php  echo $i.' ';?> votos</td>
    <?php if($identity != null && $identity->user_group == 1):?>
	<td>	
		<a class="btn btn-custom " href="/festa/edit/<?php echo $cam->getIdFesta()?>">Editar</a>
		<a class="btn btn-custom " href="/festa/moderateimg/<?php echo $cam->getIdFesta()?>">Moderar imagens</a>
        <a class="btn btn-custom " href="/festa/delete/<?php echo $cam->getIdFesta()?> " onclick="return confirm('Tem a certeza ?')">Apagar</a></td>	
	<?php endif;?>	
	
	</tr>
</table>




	
	<div id="myCarousel<?php echo '-'.$k;?>" class="carousel container slide">
  	<!-- Dot Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel<?php echo '-'.$k;?>" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel<?php echo '-'.$k;?>" data-slide-to="1"></li>
    <li data-target="#myCarousel<?php echo '-'.$k;?>" data-slide-to="2"></li>
  </ol>
  
	<!-- Items -->
  <div class="carousel-inner">
	<?php foreach ($images as $img):?>
	<?php if($cam->getIdFesta()==$img->getIdFesta()->getIdFesta()):?>
	
	
    
    <?php if($j==0):?>
    <div class="active item"><img alt=""
			src="/assets/festa/thumbs/<?php echo $img->getImagem();$j++;?>"></div>
			
    <?php else :?>	
	<div class="item"><img  alt=""
			src="/assets/festa/thumbs/<?php echo $img->getImagem();?>"></div>
			
	<?php endif;?>

	<?php endif;?>
	  
	<?php endforeach;?>
	</div>
	<!-- Navigation -->
  	  <a class="carousel-control left" href="#myCarousel<?php echo '-'.$k;?>" data-slide="prev">&lsaquo;</a>
  		<a class="carousel-control right" href="#myCarousel<?php echo '-'.$k;?>" data-slide="next">&rsaquo;</a>
	 
	</div> 

	 
	 


<?php $k++;$j=0;endforeach;} ?>


<?php

echo $this->paginationControl ( $this->festas, 'Sliding', array (
		'partial/paginator2.phtml',
		'festa' 
), array (
		'route' => 'festacamara',
		'id' => $id 
) ); 

?>
<p>
<a class="btn btn-custom " href="<?php echo $this->url('festa', array('action'=>'distrito','id'=>$distrito));?>">Voltar a pagina anterior</a>
</p>
