<?php // module/Festa/view/festa/festa/edit.phtml:



?>
<h1><?php echo $this->escapeHtml(utf8_encode('Editar Ação de Campanha')); ?></h1>

<?php if(count($flashError)) : ?>
	<div class="alert alert-error fade in">
    	<button type="button" class="close" data-dismiss="alert">x</button>
    	<?php foreach ($flashError as $msg) : ?>
    		<?php echo $msg; ?><br />
    	<?php endforeach; ?>
    	
    </div>
<?php endif; ?>

<?php if ($identity === null): ?>
<p>Para editar um cartaz, &eacute; necess&aacute;rio estar logado ou registado. Por favor fa&ccedil;a <a href="<?php echo $this->url('user',array('action'=>'login'));?>">Login</a> ou <a href="<?php echo $this->url('user',
		array('action'=>'registo'));?>">Registe-se</a></p>
<?php else: 
	$form = $this->form;
	$form->setAttribute ( 'action', $this->url ( 'festa', array (
			'action' => 'edit','id'=>$id
	) ) );
	
	$form->prepare ();
	
	echo $this->form ()->openTag ( $form );
	echo $this->formCollection ( $form );
	echo $this->form ()->closeTag ();
	endif;
?>


<p>
	<a class="btn btn-custom "
		href="<?php echo $this->url('festa', array('action'=>'moderate'));?>">Voltar
		ao Moderar</a>
</p>