<?php // module/Festa/view/festa/festa/index.phtml:?>

<h1><?php echo $this->escapeHtml(utf8_encode('moderar Imagens de Ação de Campanha')); ?></h1>
<h3><?php echo utf8_encode('seleciona as imagens que deseja guardar')?></h3>

</br>
</br>

<?php if($images!=null):?>
<table class="table">
	<?php $i=0; $j=0;?>
	<?php foreach ($images as $img):?>
	
	<?php if($i==0):?>
	<tr>
	<form name="images" action="/festa/moderateimg/<?php echo $img->getIdFesta()->getIdFesta();?>" method="post">
		<td><input type="checkbox" name="<?php  echo $img->getIdImage();?>" value="<?php echo $img->getIdImage();?>"><img width="256" alt="" src="/assets/festa/thumbs/<?php echo $img->getImagem();?>"></td>
	<?php $i++;?>
	<?php elseif($i<4):?>
		<td><input type="checkbox" name="<?php  echo $img->getIdImage();?>" value="<?php echo $img->getIdImage();?>"><img width="256" alt="" src="/assets/festa/thumbs/<?php echo $img->getImagem();?>"></td>
	<?php 
	$i++;
	elseif($i==4):?>
	</tr>
	<tr>
		<td><input type="checkbox" name="<?php echo $img->getIdImage();?>" value="<?php echo $img->getIdImage();?>"><img width="256" alt="" src="/assets/festa/thumbs/<?php echo $img->getImagem();?>"></td>
	
	<?php 
	$i=1;
	endif;?>
	
	<?php endforeach;?>
	
</tr>
<tr><td><input type="submit" value="Enviar"></form></td></tr>
</table>
<?php endif;?>
<table class="table">
<tr>

	<?php $i=0?>
	<?php foreach ($imagesact as $img):?>
	
	<?php if($i==0):?>
	<tr>
		<td><img width="256" alt="" src="/assets/festa/thumbs/<?php echo $img->getImagem();?>"></br>
		<a class="btn btn-custom" href="/festa/deleteimg/<?php echo $img->getIdImage()?> " onclick="return confirm('Tem a certeza ?')">Apagar</a></td>
	<?php $i++;?>
	<?php elseif($i<4):?>
		<td><img width="256" alt="" src="/assets/festa/thumbs/<?php echo $img->getImagem();?>"></br>
		<a class="btn btn-custom" href="/festa/deleteimg/<?php echo $img->getIdImage()?> " onclick="return confirm('Tem a certeza ?')">Apagar</a></td>
	<?php 
	$i++;
	elseif($i==4):?>
	</tr>
	<tr>
		<td><img width="256" alt="" src="/assets/festa/thumbs/<?php echo $img->getImagem();?>"></br>
		<a class="btn btn-custom" href="/festa/deleteimg/<?php echo $img->getIdImage()?> " onclick="return confirm('Tem a certeza ?')">Apagar</a></td>
	 
	<?php 
	$i=1;
	endif;?>

	<?php endforeach;?>
</tr>
</table>

<table class="table">

<?php if(isset($festas)){?>
<tr>
	<th>Distrito</th>
<th>C&acirc;mara</th>
<th>Partido</th>
<th>Morada Inserida</th>
<th>Morada Gmaps</th>
</tr>
<tr>
	<td><?php echo $festas->getIdLista()->getIdcamara()->getIdDistrito()->getNome()?></td>
	<td><?php echo $festas->getIdLista()->getIdcamara()->getNome()?></td>
	<td><?php echo $festas->getIdLista()->getNome();?></td>
	<td><?php echo $festas->getMorada();?></td>
    <td><?php echo $this->GmapHelper($festas->getCorX(), $festas->getCorY());?></td>
    <td>
    

</tr>
<?php }?>
</table>

<p>
	<a class="btn btn-custom "
		href="<?php echo $this->url('festa', array('action'=>'moderate'));?>">Voltar
		ao Moderar</a>
</p>