<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Lista extends \Application\Entity\Lista implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdLista()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idLista"];
        }
        $this->__load();
        return parent::getIdLista();
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setOrcamento($orcamento)
    {
        $this->__load();
        return parent::setOrcamento($orcamento);
    }

    public function getOrcamento()
    {
        $this->__load();
        return parent::getOrcamento();
    }

    public function setCor($cor)
    {
        $this->__load();
        return parent::setCor($cor);
    }

    public function getCor()
    {
        $this->__load();
        return parent::getCor();
    }

    public function setIdCamara(\Application\Entity\Camara $idCamara = NULL)
    {
        $this->__load();
        return parent::setIdCamara($idCamara);
    }

    public function getIdCamara()
    {
        $this->__load();
        return parent::getIdCamara();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idLista', 'nome', 'orcamento', 'cor', 'idCamara');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}