<?php echo $this->doctype(); ?>

<html lang=pt>
  <head>
    <meta charset="UTF-8">
    <?php echo $this->headTitle('Campanha Limpa')?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->appendStylesheet($this->basePath() . '/css/bootstrap.css')
                    ->appendStylesheet($this->basePath() . '/css/custom.css')
                    ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.css') ?>

    <!-- Scripts -->
	<?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                 ->appendFile($this->basePath() . '/js/jquery-1.7.2.min.js')
                                  ->appendFile($this->basePath() . '/js/bootstrap.js')
                                 ->appendFile($this->basePath() . '/js/bootstrap.min.js')
								->appendFile($this->basePath() . '/js/smoothscroll.js')

    ?>
  </head>
  <body style="background-color: #FFFFFF;">
  
  <?php echo $this->content;?>
  
  </body>
  </html>
  