<?php echo $this->doctype(); ?>

<html lang=pt>
  <head>
    <meta charset="UTF-8">
    <?php echo $this->headTitle('Campanha Limpa')?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->appendStylesheet($this->basePath() . '/css/bootstrap.css')
                    ->appendStylesheet($this->basePath() . '/css/custom.css')
                    ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.css') ?>

    <!-- Scripts -->
	<?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                 ->appendFile($this->basePath() . '/js/jquery-1.7.2.min.js')
                                  ->appendFile($this->basePath() . '/js/bootstrap.js')
                                 ->appendFile($this->basePath() . '/js/bootstrap.min.js')
								->appendFile($this->basePath() . '/js/smoothscroll.js')

    ?>
  </head>
  <body>
   
  <?php $auth = new Zend\Authentication\AuthenticationService();
  		$identity=null;
        if($auth->hasIdentity()) {
            $identity = $auth->getIdentity();
        }?>

 	<div class="navbar navbar-inverse navbar-fixed-top" >
  		<div class="navbar-inner">
    		<div class="container">
     			<button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			    </button>
      			<a href="/" class="brand"><img src="/images/logoc.png" height="60" width="200" alt=""></a>
      				<div class="nav-collapse collapse">
        				<ul class="nav">
        				<div class="autenticar_registar">
          					<?php if($identity === null): ?>
                
								<a href="<?php echo $this->url('user',
								array('action'=>'login'));?>" class="navbar-link">Autenticar</a> /
								<a href="<?php echo $this->url('user',
								array('action'=>'registo'));?>" class="navbar-link">Registar</a>
					  
				    		<?php else: ?>
				    			
								Seja Bem-Vindo <strong class="username"><?php echo $identity->username ?></strong>.
							    <a href="<?php echo $this->url("user",array("action" => "logout"));?>"class="navbar-link">Sair</a>
				   
				    		<?php endif; ?>
				    	</div>
            			<ul class="nav">
			              <?php if ($identity == null){ ?>
			              <li><a href="/#sobre" class="smoothScroll">Sobre</a></li>
			              <li><a href="/#estatisticas" class="smoothScroll">Estatísticas</a></li>
			              <li><a href="/#cartaz"  class="smoothScroll">Cartazes</a></li>
			              <li><a href="/#brindes" class="smoothScroll">Brindes</a>
			              <li><a href="/#comicio" class="smoothScroll">A&ccedil;&otilde;es</a></li>         
			              <li><a href="/#documentos" class="smoothScroll">Legisla&ccedil;&atilde;o</a></li>
			              <li><a href="/#ficha_tecnica" class="smoothScroll">Ficha T&eacute;cnica</a></li>
			              <?php } ?>
			              <?php if($auth->hasIdentity()) {
				                	if($identity->user_group == 1){?>
					                	<li><a href="/post-cartaz/moderate">Moderar Cartaz</a></li>
					                	<li><a href="/post-brinde/moderate">Moderar Brinde</a></li>
					                	<li><a href="/festa/moderate">Moderar Comício</a></li>
			              <?php }}?>
			              <?php if($auth->hasIdentity()) {
			              			if($identity->user_group == 0){?>
						              <li><a href="/#sobre" class="smoothScroll">Sobre</a></li>
						              <li><a href="/#estatisticas" class="smoothScroll">Estatísticas</a></li>
						              <li><a href="/#cartaz"  class="smoothScroll">Cartazes</a></li>
						              <li><a href="/#brindes" class="smoothScroll">Brindes</a>
						              <li><a href="/#comicio" class="smoothScroll">A&ccedil;&otilde;es</a></li>            
						              <li><a href="/#documentos" class="smoothScroll">Legisla&ccedil;&atilde;o</a></li>
						              <li><a href="/#ficha_tecnica" class="smoothScroll">Ficha T&eacute;cnica</a></li>
              			<?php }}?>
            		   </ul>
            		   </ul>
          		   </div>
           	  </div>
      	 </div>
    </div>
 
 
   
<div class="container-fluid"><!--container starts -->

<div class="row-fluid"><!--second row starts -->
	<?php echo $this->content;?>
	<div class="push">&nbsp;</div>
</div>
</div>



    

                   
                    
             
               
               
                

	

 

<!-- Bootstrap js -->


	
    



<div class="span12" style="width:100%; background-color: #673337;
  background-image: -moz-linear-gradient(top, #b53335, #673337);
  background-image: -ms-linear-gradient(top, #b53335, #673337);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#b53335), to(#673337));
  background-image: -webkit-linear-gradient(top, #b53335, #673337);
  background-image: -o-linear-gradient(top, #b53335, #673337);
  background-image: linear-gradient(top, #b53335, #673337);
  background-repeat: repeat-x;
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#b53335', endColorstr='#673337', GradientType=0);
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
  -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25), inset 0 -1px 0 rgba(0, 0, 0, 0.1);
  -moz-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25), inset 0 -1px 0 rgba(0, 0, 0, 0.1);
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25), inset 0 -1px 0 rgba(0, 0, 0, 0.1); border-top: 0 none;
    margin-bottom: 0;
    margin-top: 0;
    padding: 0;
     margin:0px;">
   

<hr align="center">


<footer class ="footer" style="text-align:center"><b>&copy; 2013</b> <a style="color:#0397d6;" href="http://transparencia.pt" target="_blank"><b>TIAC</b></a><b>. Todos os direitos reservados. - Mastered by </b><a style="color:#0397d6;" href="http://dmanlancers.byethost16.com" target="_blank"><b>dm@nl@ncers</b></a></footer>
</div>

  </body>
</html>
