
<?php
// module/User/view/user/user/index.phtml:
?>

<h1><?php echo $this->escapeHtml('Utilizador'); ?></h1>
<p>
	<?php if($identity === null): ?>
	<a href="<?php echo $this->url('user', array('action' => 'registo')); ?>">Registo</a><br/>
    <a href="<?php echo $this->url('user', array('action' => 'login')); ?>">Login</a><br/>
    <?php else: ?>
    <a href="<?php echo $this->url('user', array('action' => 'logout')); ?>">Logout</a><br/>
     <?php endif; ?>
    
</p>
<!--<p>-->
    <?php /*if($identity === null): ?>
    Not logged in.
    <?php else: ?>
    Logged in as <strong><?php echo $identity->username ?></strong>.
    <?php endif; ?>
</p>*/