<?php
// module/Candidatura/view/candidatura/candidatura/distrito.phtml:
?>

<h1><?php echo $this->escapeHtml($distrito); ?></h1>
</br>
<h2>Escolha um concelho.</h2>
</br>
</br>

<select onchange="javascript:location.href='/candidatura/'+this.options
    [this.selectedIndex].value;">
        <option selected="selected">Concelhos</option>
<?php foreach ($camaras as $cam) : ?>
	<option VALUE="<?php echo $this->escapeHtml($cam->id);?>"><?php echo $this->escapeHtml($cam->nome);?></option>

<?php endforeach; ?>

</select>

</br>
</br>

<p>
<a class="btn btn-custom" href="<?php echo $this->url('candidatura', array('action'=>'todas'));?>">Voltar aos Distritos</a>
</p>