<?php
// module/Candidatura/view/candidatura/candidatura/independente.phtml
?>

<h1><?php echo $this->escapeHtml('Adicionar uma nova candidatura'); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('candidatura', array('action' => 'independente','id'=>$id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>
<p>
<a href="<?php echo $this->url('camara', array('action'=>'index','id'=>$distrito));?>">Voltar as Camaras do distrito</a>
</p>
