



<table class="table">
<tr>
<th>Distrito</th>
<th>Id Camara</th>
<th>Camara</th>
<th>Lista</th>
<th>Orcamento</th>
<th>&nbsp;</th>
</tr>
<?php foreach ($candidatura as $cam) : ?>
<tr>
	<td><?php echo $this->escapeHtml($cam->getIdCamara()->getIdDistrito()->getNome());?></td>
	<td><?php echo $this->escapeHtml($cam->getIdCamara()->getIdCamara());?></td>
    <td><?php echo $this->escapeHtml($cam->getIdCamara()->getNome());?></td>
    <td><?php echo $this->escapeHtml($cam->getNome());?></td>
    <td><?php echo $this->escapeHtml($cam->getOrcamento());?></td>
    <td><a href="/candidatura/orca/<?php echo $cam->getIdLista();?>">adicionar orcamento</a>
   
</tr>

<?php endforeach; ?>
</table>