<?php
// module/Camara/view/camara/camara/index.phtml:

$title = 'Selecionar distrito';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<table class="table">
<tr>
    <th>Tamanho</th>
    <th>Pre&ccedil;o</th>
    
</tr>
<?php foreach ($cartaz as $cam) : ?>
<tr>
    <td><?php echo $this->escapeHtml($cam->tamanho);?></td>
    <td><?php echo $this->escapeHtml($cam->preco);?></td>
    
    
</tr>

<?php endforeach; ?>
</table>

<?php
	$form = $this->form;
	$form->setAttribute ( 'action', $this->url ( 'cartaz', array (
			'action' => 'index'
	) ) );
	
	$form->prepare ();
	
	echo $this->form ()->openTag ( $form );
	echo $this->formCollection ( $form );
	echo $this->form ()->closeTag ();

?>
