



<script>






$(function(){

	var all = new Array(); 
	var id = <?php echo json_encode($id);?>;
	var id2 = <?php echo json_encode($id2);?>;
	var id3 = <?php echo json_encode($id3);?>;
	var id4 = <?php echo json_encode($id4);?>;
	var id5 = <?php echo json_encode($id5);?>;
	

$.getJSON("/ranking-rest/" + id, function (data) {
	if(id>0){
	all.push(data);
}

	console.log(all);
	$.getJSON("/ranking-rest/" + id2, function (data) {
		if(id2>0){
		all.push(data);
		}	
		$.getJSON("/ranking-rest/" + id3, function (data) {
			if(id3>0){
				all.push(data);
				}
		
			$.getJSON("/ranking-rest/" + id4, function (data) {
				if(id4>0){
					all.push(data);
					}
				
				$.getJSON("/ranking-rest/" + id5, function (data) {
					if(id5>0){
						all.push(data);
						}
				

				console.log(all);
		

	                $("#chartContainer").dxChart({
	                	dataSource: all,
	                	animation:false,
    commonSeriesSettings: {
        argumentField: "state",
        type: "bar",
        hoverMode: "allArgumentPoints",
        selectionMode: "allArgumentPoints",
        label: {
            visible: true,
            format: "fixedPoint",
            precision: 0,

			 
        },
			
    },
    valueAxis: {
            visible: true,
            label: {
                customizeText: function () {
                    return this.value + ' pontos';
                }
            },
            min: 0,
            max: 80
        },

	                    series: [
	                        { valueField: "A", name: " Organização,Composição  <br/>e Funcionamento" },
	                        { valueField: "B", name: "Planos e Relatórios<br/> [2 anos anteriores]" },
	                        { valueField: "C", name: "Taxas e Regulamentos" },
	                        { valueField: "D", name: "Relação com a Sociedade" },
	                        { valueField: "E", name: "Contratação Pública" },
	                        { valueField: "F", name: "Informação Económico-Financeira" },
	                        { valueField: "G", name: "Urbanismo" },
	                    ],
	                    title: "Ranking Dimensões ITM:",
	                	
	                		 tooltip: {
	                			 enabled: true,
	                			 customizeText: function (e) {
	                				 return e.valueText + ' Pontos ';
	                				 }
	                		},
	                    legend: {
	                        verticalAlignment: "bottom",
	                        horizontalAlignment: "center"
	                    },
	                	
	                    pointClick: function (point) {
	                        this.select();
	                    }
	                });

	});

});

});


});
		

});
		              

});
</script>








<div class="hero">
        	

<div class="col-xs-12">
	
		<div id="chartContainer" style="width: 1000px;; height:600px;background:none;border:hidden;"></div>

</div>
 
 <div  style="margin-top:15px;"><img  src="/images/logoc.png"/></div>
</div>

     


